# Generated by Django 3.2.3 on 2021-06-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_comments_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
